name: Test Workflow for Staging

on:
  push:
    branches:
      - staging

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend-server

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install and Upgrade pip
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip

      - name: Install Dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Tests
        run: |
          python -m unittest discover -s tests
